-- ============================================================
-- Migration: unitholder_certificate email template
-- Date: 2026-04-25
-- Template key: unitholder_certificate
-- Used by: admin/unit_issuance.php on unit issue
-- Note: HTML rendering by mailer.php uses payload_json fields.
--   The body_text here is the plain-text fallback / mailer
--   preview. The full styled HTML is generated by the
--   certificate template in the mailer send path.
-- ============================================================

INSERT IGNORE INTO `email_templates`
    (`template_key`, `subject_line`, `body_text`, `is_active`, `created_at`, `updated_at`)
VALUES
(
  'unitholder_certificate',
  'COG$ Certificate of Unit Holding — {{unit_class_name}} — {{cert_ref}}',
  'Dear {{first_name}},\n\nThis email confirms that the Caretaker Trustee of the COGS of Australia Foundation Community Joint Venture Mainspring Hybrid Trust (ABN 61 734 327 831) has lawfully issued units to you under Sub-Trust A of the CJVM Hybrid Trust Declaration.\n\nCERTIFICATE OF UNIT HOLDING\n\nCertificate Reference: {{cert_ref}}\nRegister Reference: {{register_ref}}\nUnitholder: {{full_name}}\nMember Number: {{member_number}}\nUnit Class: {{unit_class_name}} (Class {{unit_class_code}})\nUnits Issued: {{units_issued}}\nIssue Date: {{issue_date}}\nCryptographic Record (SHA-256): {{sha256_hash}}\n\nRIGHTS AND ATTRIBUTES ATTACHING TO YOUR UNITS:\nThe rights, restrictions, and smart contract attributes programmed into the corresponding COG$ Token are detailed in the attached PDF certificate. These are class-specific and are drawn directly from the CJVM Hybrid Trust Declaration and Sub-Trust A Deed.\n\nGOVERNING INSTRUMENTS:\nJoint Venture Participation Agreement | CJVM Hybrid Trust Declaration | Sub-Trust A Deed\nGoverning Law: South Australia, Australia\n\nThis certificate is issued by:\nThomas Boyd Cunliffe\nCaretaker Trustee\nCOGS of Australia Foundation\nDrake Village NSW 2469 | Wahlubal Country, Bundjalung Nation\n\nFor questions, contact: members@cogsaustralia.org\nFoundation website: https://cogsaustralia.org',
  1,
  NOW(),
  NOW()
);
-- Note: INSERT IGNORE used — template_key has no UNIQUE constraint in email_templates.
-- If row already exists, INSERT is silently skipped. Update via admin Email Templates page.
